/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import lesson_panel.LESSON_11;
import javax.swing.*;
import lesson_panel.LESSON_12;
import lesson_panel.LESSON_13;
import lesson_panel.LESSON_14;
import lesson_panel.LESSON_15;


/**
 *
 * @author intsi
 */
public class menu_2 extends javax.swing.JPanel {

    /**
     * Creates new form menu_222
     */
    public menu_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        less2 = new javax.swing.JLabel();
        lesson3 = new javax.swing.JButton();
        less3 = new javax.swing.JLabel();
        lesson1 = new javax.swing.JButton();
        less4 = new javax.swing.JLabel();
        lesson4 = new javax.swing.JButton();
        less5 = new javax.swing.JLabel();
        less1 = new javax.swing.JLabel();
        lesson2 = new javax.swing.JButton();
        lesson5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        less2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        less2.setText("CHINESE ALPHABET ");

        lesson3.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lesson3.setText("LESSON 3");
        lesson3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lesson3ActionPerformed(evt);
            }
        });

        less3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        less3.setText("CHINESE GREETINGS ");

        lesson1.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lesson1.setText("LESSON 1");
        lesson1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lesson1ActionPerformed(evt);
            }
        });

        less4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        less4.setText("CHINESE COUNTINGS");

        lesson4.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lesson4.setText("LESSON 4");
        lesson4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lesson4ActionPerformed(evt);
            }
        });

        less5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        less5.setText("BASIC CHINESE GRAMMAR");

        less1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        less1.setText("INTRODUCTION TO THE CHINESE LANGUAGE");

        lesson2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lesson2.setText("LESSON 2");
        lesson2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lesson2ActionPerformed(evt);
            }
        });

        lesson5.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lesson5.setText("LESSON 5");
        lesson5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lesson5MouseClicked(evt);
            }
        });
        lesson5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lesson5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(less4)
                            .addComponent(less3)
                            .addComponent(less5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(less1)
                            .addComponent(less2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(lesson1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(lesson2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lesson4)
                            .addComponent(lesson3)
                            .addComponent(lesson5))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(less1)
                .addGap(18, 18, 18)
                .addComponent(lesson1)
                .addGap(40, 40, 40)
                .addComponent(less2)
                .addGap(18, 18, 18)
                .addComponent(lesson2)
                .addGap(37, 37, 37)
                .addComponent(less3)
                .addGap(18, 18, 18)
                .addComponent(lesson3)
                .addGap(57, 57, 57)
                .addComponent(less4)
                .addGap(22, 22, 22)
                .addComponent(lesson4)
                .addGap(40, 40, 40)
                .addComponent(less5)
                .addGap(18, 18, 18)
                .addComponent(lesson5)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("LESSON CONTENT/CHINESE");

        jLabel1.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel1.setText("LESSONS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(169, 169, 169)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(944, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(738, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lesson1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lesson1ActionPerformed
    // Ensure the session key matches the one set during login
    Integer userId = (Integer) SessionManager.getSessionValue("userId");

    if (userId == null) {
        // If user_id is not set, show an error or handle accordingly
        JOptionPane.showMessageDialog(this, "Please log in to proceed to the lesson.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Create the new frame and set up LESSON_11 panel
    JFrame lesson11Frame = new JFrame("Lesson 1");
    LESSON_11 lesson11Panel = new LESSON_11();

    // Set default close operation and add the LESSON_11 panel
    lesson11Frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    lesson11Frame.add(lesson11Panel);
    lesson11Frame.setSize(600, 400); // Adjust frame size as needed
    lesson11Frame.setLocationRelativeTo(null); // Center the frame on the screen
    lesson11Frame.setVisible(true); // Make the frame visible
    }//GEN-LAST:event_lesson1ActionPerformed

    private void lesson2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lesson2ActionPerformed
    // Ensure the session key matches the one set during login
    Integer userId = (Integer) SessionManager.getSessionValue("userId");

    if (userId == null) {
        // If user_id is not set, show an error or handle accordingly
        JOptionPane.showMessageDialog(this, "Please log in to proceed to the lesson.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Create the new frame and set up LESSON_11 panel
    JFrame lesson12Frame = new JFrame("Lesson 2");
    LESSON_12 lesson11Panel = new LESSON_12();

    // Set default close operation and add the LESSON_11 panel
    lesson12Frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    lesson12Frame.add(lesson11Panel);
    lesson12Frame.setSize(600, 400); // Adjust frame size as needed
    lesson12Frame.setLocationRelativeTo(null); // Center the frame on the screen
    lesson12Frame.setVisible(true); // Make the frame visible
    }//GEN-LAST:event_lesson2ActionPerformed

    private void lesson3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lesson3ActionPerformed
            // Ensure the session key matches the one set during login
    Integer userId = (Integer) SessionManager.getSessionValue("userId");

    if (userId == null) {
        // If user_id is not set, show an error or handle accordingly
        JOptionPane.showMessageDialog(this, "Please log in to proceed to the lesson.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Create the new frame and set up LESSON_11 panel
    JFrame lesson13Frame = new JFrame("Lesson 3");
    LESSON_13 lesson13Panel = new LESSON_13();

    // Set default close operation and add the LESSON_11 panel
    lesson13Frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    lesson13Frame.add(lesson13Panel);
    lesson13Frame.setSize(600, 400); // Adjust frame size as needed
    lesson13Frame.setLocationRelativeTo(null); // Center the frame on the screen
    lesson13Frame.setVisible(true); // Make the frame visible
    }//GEN-LAST:event_lesson3ActionPerformed

    private void lesson4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lesson4ActionPerformed
                    // Ensure the session key matches the one set during login
    Integer userId = (Integer) SessionManager.getSessionValue("userId");

    if (userId == null) {
        // If user_id is not set, show an error or handle accordingly
        JOptionPane.showMessageDialog(this, "Please log in to proceed to the lesson.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Create the new frame and set up LESSON_11 panel
    JFrame lesson14Frame = new JFrame("Lesson 4");
    LESSON_14 lesson14Panel = new LESSON_14();

    // Set default close operation and add the LESSON_11 panel
    lesson14Frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    lesson14Frame.add(lesson14Panel);
    lesson14Frame.setSize(600, 400); // Adjust frame size as needed
    lesson14Frame.setLocationRelativeTo(null); // Center the frame on the screen
    lesson14Frame.setVisible(true); // Make the frame visible
    }//GEN-LAST:event_lesson4ActionPerformed

    private void lesson5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lesson5ActionPerformed
                       // Ensure the session key matches the one set during login
    Integer userId = (Integer) SessionManager.getSessionValue("userId");

    if (userId == null) {
        // If user_id is not set, show an error or handle accordingly
        JOptionPane.showMessageDialog(this, "Please log in to proceed to the lesson.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Create the new frame and set up LESSON_11 panel
    JFrame lesson15Frame = new JFrame("Lesson 5");
    LESSON_15 lesson15Panel = new LESSON_15();

    // Set default close operation and add the LESSON_11 panel
    lesson15Frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    lesson15Frame.add(lesson15Panel);
    lesson15Frame.setSize(600, 400); // Adjust frame size as needed
    lesson15Frame.setLocationRelativeTo(null); // Center the frame on the screen
    lesson15Frame.setVisible(true); // Make the frame visible
    }//GEN-LAST:event_lesson5ActionPerformed

    private void lesson5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lesson5MouseClicked
                        // Ensure the session key matches the one set during login
    Integer userId = (Integer) SessionManager.getSessionValue("userId");

    if (userId == null) {
        // If user_id is not set, show an error or handle accordingly
        JOptionPane.showMessageDialog(this, "Please log in to proceed to the lesson.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Create the new frame and set up LESSON_11 panel
    JFrame lesson15Frame = new JFrame("Lesson 5");
    LESSON_15 lesson15Panel = new LESSON_15();

    // Set default close operation and add the LESSON_11 panel
    lesson15Frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    lesson15Frame.add(lesson15Panel);
    lesson15Frame.setSize(600, 400); // Adjust frame size as needed
    lesson15Frame.setLocationRelativeTo(null); // Center the frame on the screen
    lesson15Frame.setVisible(true); // Make the frame visible
    }//GEN-LAST:event_lesson5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel less1;
    private javax.swing.JLabel less2;
    private javax.swing.JLabel less3;
    private javax.swing.JLabel less4;
    private javax.swing.JLabel less5;
    private javax.swing.JButton lesson1;
    private javax.swing.JButton lesson2;
    private javax.swing.JButton lesson3;
    private javax.swing.JButton lesson4;
    private javax.swing.JButton lesson5;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
}
