/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import lesson_panel.LESSON_16;
import javax.swing.*;
import lesson_panel.LESSON_17;
import lesson_panel.LESSON_18;
import lesson_panel.LESSON_19;
import lesson_panel.LESSON_20;

/**
 *
 * @author intsi
 */
public class menu_3 extends javax.swing.JPanel {

    /**
     * Creates new form menu_222
     */
    public menu_3() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        less7 = new javax.swing.JLabel();
        lesson8 = new javax.swing.JButton();
        leson10 = new javax.swing.JButton();
        less8 = new javax.swing.JLabel();
        less9 = new javax.swing.JLabel();
        lesson9 = new javax.swing.JButton();
        less10 = new javax.swing.JLabel();
        less6 = new javax.swing.JLabel();
        lesson7 = new javax.swing.JButton();
        lesson6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        less7.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        less7.setText("JAPANESE ALPHABET ");

        lesson8.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lesson8.setText("LESSON 3");
        lesson8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lesson8ActionPerformed(evt);
            }
        });

        leson10.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        leson10.setText("LESSON 5");
        leson10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leson10ActionPerformed(evt);
            }
        });

        less8.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        less8.setText("JAPANESE GREETINGS ");

        less9.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        less9.setText("JAPANESE COUNTINGS");

        lesson9.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lesson9.setText("LESSON 4");
        lesson9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lesson9ActionPerformed(evt);
            }
        });

        less10.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        less10.setText("BASIC JAPANESE GRAMMAR");

        less6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        less6.setText("INTRODUCTION TO THE JAPANESE LANGUAGE");

        lesson7.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lesson7.setText("LESSON 2");
        lesson7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lesson7ActionPerformed(evt);
            }
        });

        lesson6.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lesson6.setText("LESSON 1");
        lesson6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lesson6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(lesson6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(less9)
                            .addComponent(less8)
                            .addComponent(less10)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(less7)
                            .addComponent(less6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(lesson7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(leson10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lesson9)
                                .addComponent(lesson8)))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(less6)
                .addGap(18, 18, 18)
                .addComponent(lesson6)
                .addGap(30, 30, 30)
                .addComponent(less7)
                .addGap(28, 28, 28)
                .addComponent(lesson7)
                .addGap(37, 37, 37)
                .addComponent(less8)
                .addGap(18, 18, 18)
                .addComponent(lesson8)
                .addGap(57, 57, 57)
                .addComponent(less9)
                .addGap(31, 31, 31)
                .addComponent(lesson9)
                .addGap(31, 31, 31)
                .addComponent(less10)
                .addGap(27, 27, 27)
                .addComponent(leson10)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("LESSON CONTENT/JAPANESE");

        jLabel1.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel1.setText("LESSONS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(642, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lesson6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lesson6ActionPerformed
        // Ensure the session key matches the one set during login
        Integer userId = (Integer) SessionManager.getSessionValue("userId");

        if (userId == null) {
            // If user_id is not set, show an error or handle accordingly
            JOptionPane.showMessageDialog(this, "Please log in to proceed to the lesson.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Create the new frame and set up LESSON_16 panel
        JFrame lessonFrame = new JFrame("Lesson 1");  // Create a new JFrame
        LESSON_16 lesson16Panel = new LESSON_16();  // Assume LESSON_16 is a JPanel

        lessonFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  // Close the frame when done
        lessonFrame.add(lesson16Panel);  // Add the panel to the frame
        lessonFrame.setSize(800, 600);  // Set the size of the frame
        lessonFrame.setLocationRelativeTo(null);  // Center the frame on the screen
        lessonFrame.setVisible(true);  // Make the frame visible

    }//GEN-LAST:event_lesson6ActionPerformed

    private void lesson7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lesson7ActionPerformed
            // Ensure the session key matches the one set during login
    Integer userId = (Integer) SessionManager.getSessionValue("userId");

    if (userId == null) {
        // If user_id is not set, show an error or handle accordingly
        JOptionPane.showMessageDialog(this, "Please log in to proceed to the lesson.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Create the new frame and set up LESSON_11 panel
    JFrame lesson17Frame = new JFrame("Lesson 2");
    LESSON_17 lesson17Panel = new LESSON_17();

    // Set default close operation and add the LESSON_11 panel
    lesson17Frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    lesson17Frame.add(lesson17Panel);
    lesson17Frame.setSize(600, 400); // Adjust frame size as needed
    lesson17Frame.setLocationRelativeTo(null); // Center the frame on the screen
    lesson17Frame.setVisible(true); // Make the frame visible
    }//GEN-LAST:event_lesson7ActionPerformed

    private void lesson8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lesson8ActionPerformed
                 // Ensure the session key matches the one set during login
    Integer userId = (Integer) SessionManager.getSessionValue("userId");

    if (userId == null) {
        // If user_id is not set, show an error or handle accordingly
        JOptionPane.showMessageDialog(this, "Please log in to proceed to the lesson.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Create the new frame and set up LESSON_11 panel
    JFrame lesson18Frame = new JFrame("Lesson 3");
    LESSON_18 lesson18Panel = new LESSON_18();

    // Set default close operation and add the LESSON_11 panel
    lesson18Frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    lesson18Frame.add(lesson18Panel);
    lesson18Frame.setSize(600, 400); // Adjust frame size as needed
    lesson18Frame.setLocationRelativeTo(null); // Center the frame on the screen
    lesson18Frame.setVisible(true); // Make the frame visible
    }//GEN-LAST:event_lesson8ActionPerformed

    private void lesson9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lesson9ActionPerformed
                         // Ensure the session key matches the one set during login
    Integer userId = (Integer) SessionManager.getSessionValue("userId");

    if (userId == null) {
        // If user_id is not set, show an error or handle accordingly
        JOptionPane.showMessageDialog(this, "Please log in to proceed to the lesson.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Create the new frame and set up LESSON_11 panel
    JFrame lesson19Frame = new JFrame("Lesson 4");
    LESSON_19 lesson19Panel = new LESSON_19();

    // Set default close operation and add the LESSON_11 panel
    lesson19Frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    lesson19Frame.add(lesson19Panel);
    lesson19Frame.setSize(600, 400); // Adjust frame size as needed
    lesson19Frame.setLocationRelativeTo(null); // Center the frame on the screen
    lesson19Frame.setVisible(true); // Make the frame visible
    }//GEN-LAST:event_lesson9ActionPerformed

    private void leson10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leson10ActionPerformed
                         // Ensure the session key matches the one set during login
    Integer userId = (Integer) SessionManager.getSessionValue("userId");

    if (userId == null) {
        // If user_id is not set, show an error or handle accordingly
        JOptionPane.showMessageDialog(this, "Please log in to proceed to the lesson.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Create the new frame and set up LESSON_11 panel
    JFrame lesson20Frame = new JFrame("Lesson 5");
    LESSON_20 lesson20Panel = new LESSON_20();

    // Set default close operation and add the LESSON_11 panel
    lesson20Frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    lesson20Frame.add(lesson20Panel);
    lesson20Frame.setSize(600, 400); // Adjust frame size as needed
    lesson20Frame.setLocationRelativeTo(null); // Center the frame on the screen
    lesson20Frame.setVisible(true); // Make the frame visible
    }//GEN-LAST:event_leson10ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton leson10;
    private javax.swing.JLabel less10;
    private javax.swing.JLabel less6;
    private javax.swing.JLabel less7;
    private javax.swing.JLabel less8;
    private javax.swing.JLabel less9;
    private javax.swing.JButton lesson6;
    private javax.swing.JButton lesson7;
    private javax.swing.JButton lesson8;
    private javax.swing.JButton lesson9;
    // End of variables declaration//GEN-END:variables
        private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
