/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lesson_panel;

import com.raven.form.SessionManager;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author intsi
 */
public class LESSON_11 extends javax.swing.JPanel {

    /**
     * Creates new form LESSON_11
     */
      

    
    public LESSON_11() {
        initComponents();
}
    
    public void loginUser(int userId) {
    SessionManager.setSessionValue("userId", userId);  // Use "userId" to store the session
    System.out.println("User ID set in session: " + userId);
}

private boolean hasUserTakenQuiz(int quizId) {
    Integer userId = (Integer) SessionManager.getSessionValue("userId");  // Use "userId"
    if (userId == null) {
        JOptionPane.showMessageDialog(this, "Please log in to take the quiz.", "Error", JOptionPane.ERROR_MESSAGE);
        return true; // Prevent quiz if not logged in
    }

    String query = "SELECT COUNT(*) FROM responses WHERE user_id = ? AND quiz_id = ?";
    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/users-database", "root", "");
         PreparedStatement stmt = conn.prepareStatement(query)) {

        stmt.setInt(1, userId);
        stmt.setInt(2, quizId);
        ResultSet rs = stmt.executeQuery();

        if (rs.next() && rs.getInt(1) > 0) {
            JOptionPane.showMessageDialog(this, "You have already taken this quiz.", "Error", JOptionPane.ERROR_MESSAGE);
            return true; // User has already taken the quiz
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    return false; // User can take the quiz
}
    public static void main(String[] args) {
      
        // Create a JFrame
        JFrame frame = new JFrame();

        // Set the frame undecorated
        frame.setUndecorated(true);

        // Add the LESSON_11 JPanel to the frame
        LESSON_11 lessonPanel = new LESSON_11();
        frame.add(lessonPanel);

        // Set frame size and location
        frame.setSize(1200, 800); // Make the frame larger
        frame.setLocationRelativeTo(null); // Center the frame on the screen

        // Add a close button (optional, since no title bar is available)
        JButton closeButton = new JButton("Close");
        closeButton.setBounds(1100, 10, 80, 30); // Position it near the top-right
        lessonPanel.setLayout(null); // Use null layout for custom positioning
        lessonPanel.add(closeButton);

        closeButton.addActionListener(e -> System.exit(0)); // Close the application

        // Set frame visibility
        frame.setVisible(true);

        // Ensure the application exits when the frame is closed
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        takequiz = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        scroll_panel1 = new com.raven.swing.noticeboard.scroll_panel();

        setPreferredSize(new java.awt.Dimension(1862, 712));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1544, 931));
        jPanel1.setLayout(null);

        takequiz.setText("Take Quiz");
        takequiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takequizActionPerformed(evt);
            }
        });
        jPanel1.add(takequiz);
        takequiz.setBounds(1080, 600, 150, 60);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("What is Mandarin? \n\nMandarin (Mandarin Chinese, or standard Chinese as we know it with the familiar four tones) is the only official language of China at a national level and one of the working languages of the United Nations. \nIt was first documented in the Yuan Dynasty in 14th century China and was later standardized and advocated as the national language after the founding of the People’s Republic of China in 1949. \nMandarin is the native language of 920 million people living in northern and southwestern China, who constitute 65.7% of China’s population. \nPeople from other areas of China generally speak another variety of Chinese (e.g. Cantonese, Hokkien, Hakka, Shanghainese) as their first language, yet most of them can speak Mandarin fluently as a second language after learning it in school.\nOutside China (PRC), Mandarin is spoken as the official language of Taiwan, as well as one of the four official languages of Singapore.\nMandarin’s vocabulary, pronunciation, and tone rules vary by major region (from Heilongjiang Province in the northeast all the way down to Yunnan in the southwest), but the language is essentially the same.\nIn Beijing, the form is called 北京话 (Běijīng huà), meaning Beijing language, or Beijing dialect. In Sichuan, where the language is similar but with apparent pronunciation and tone differences, the dialect is called 四川话 (Sìchuān huà) – Sichuan language.\n\n\nIN CHINESE MANDARIN\n\nMandarin (Mandarin Chinese, huòzhě wǒmen shóuxī de biāozhǔn Hànyǔ, dài yǒu sì gè shēngdiào) shì Zhōngguó guónèi wéi yī de guójiā jí gōngyòng yǔyán, yě shì Liánhéguó de gōngzuò yǔyán zhī yī. \nTā zuìzǎo zài Yuáncháo (14 shìjì de Zhōngguó) bèi jìzǎi, zài Zhōnghuá Rénmín Gònghéguó chénglì hòu de 1949 nián bèi biāozhǔnhuà bìng tuīguǎng wéi guóyǔ.\nMandarin shì jūzhù zài Zhōngguó běifāng hé xīnán dìqū de 9.2 yì rén de mǔyǔ, zhàn Zhōngguó rénkǒu de 65.7%. \nQítā dìqū de Zhōngguórén tōngcháng yǐ qítā de Zhōngwén fāngyán (rú Guǎngdōnghuà, Mǐnnánhuà, Kèjiāhuà, Shànghǎihuà) wéi mǔyǔ, dànshì dàduō shù rén tōngguò xuéxiào xuéxí, néng liúlì dì jiǎng Hànyǔ zuòwéi èryǔ.\nZài Zhōngguó (Zhōnghuá Rénmín Gònghéguó) yǐwài, Mandarin shì Táiwān de guānfāng yǔyán, yěshì Xīnjiāpō de sì zhǒng guānfāng yǔyán zhī yī.\nMandarin de cíhuì, fāyīn, hé shēngdiào guīzé huì gēnjù zhǔyào dìqū chūxiàn biànhuà (cóng Dōngběi de Hēilóngjiāng shěng dào xīnán de Yúnnán shěng), dàn qí yǔyán jīběn xiāngtóng.\nZài Běijīng, zhè zhǒng yǔyán bèi jiàozuò 北京话 (Běijīng huà), yìsi shì Běijīng de yǔyán, huò Běijīng fāngyán. \nZài Sìchuān, zhè zhǒng yǔyán lèisì dàn fāyīn hé shēngdiào yǒu xiǎnrán chāyì, zhè bèi chēngzuò 四川话 (Sìchuān huà) – Sìchuān de yǔyán.\n");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 1940, 960);
        jPanel1.add(scroll_panel1);
        scroll_panel1.setBounds(0, 0, 1350, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1935, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void takequizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takequizActionPerformed
        // Check if the user is logged in by verifying the session for a valid userId
        Integer userId = (Integer) SessionManager.getSessionValue("userId");

        System.out.println("Logged in user ID: " + userId);  // Debug print

        if (userId == null) {
            // If user_id is not set, show a message asking the user to log in
            JOptionPane.showMessageDialog(this, "Please log in to take the quiz.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit the method if the user is not logged in
        }

        int quizId = 1; // Assume this is the quiz ID

        if (hasUserTakenQuiz(quizId)) {
            // If the user has already taken the quiz, exit the method
            return;
        }

        // Open quiz window
        Quiz_11 quizFrame = new Quiz_11(quizId);
        quizFrame.setVisible(true);
        quizFrame.pack();
        quizFrame.setLocationRelativeTo(null);

        // Dispose of current frame
        JFrame parentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentFrame != null) {
            parentFrame.dispose();
        }
    }//GEN-LAST:event_takequizActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private com.raven.swing.noticeboard.scroll_panel scroll_panel1;
    private javax.swing.JButton takequiz;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void pack() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
