/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lesson_panel;

import com.raven.form.SessionManager;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author intsi
 */
public class LESSON_18 extends javax.swing.JPanel {

    /**
     * Creates new form LESSON_13
     */
    public LESSON_18() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        takequiz = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jTextArea6.setRows(5);
        jTextArea6.setText("\n\n11. Douitashimashite\n       (You’re Welcome)\n12. Sumimasen\n       (Excuse me)\n13. Gomennasai\n       (I am sorry)\n14. O-negai shimasu\n        (Please)\n15. Itadakimasu\n        (before eating)\n16. Gochisousamadeshita\n        (After eating)\n17. Moshi Moshi?\n         (Hello)\n18. Oyasuminasai\n         (Good night)\n19. Mata ashita\n         (See you tomorrow)\n20. Sayounara\n        (Goodbye)");
        jScrollPane6.setViewportView(jTextArea6);

        takequiz.setText("Take Quiz");
        takequiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takequizActionPerformed(evt);
            }
        });

        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jTextArea7.setRows(5);
        jTextArea7.setText("\n\n1. Ohayou\n       (Good Morning (casual)\n2. Ohayou Gozaimasu\n      (Good Morning(polite)\n3. Konnichiwa\n      (Hello)\n4. Konbanwa\n      (Good Evening)\n5. Hajimemashite\n      (Nice to meet you)\n6. desu ka?\n      (How are you)\n7. Genki desu\n      (I’m Fine)\n8. Hai\n      (Yes)\n9. Arigatou\n      (Thank You)\n10. Arigatou Gozaimasu\n     (Thank you very much)");
        jScrollPane7.setViewportView(jTextArea7);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("JAPANESE GREETINGS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(951, 951, 951)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138)
                                .addComponent(takequiz, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(takequiz, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(800, 800, 800))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void takequizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takequizActionPerformed
        // Check if the user is logged in by verifying the session for a valid userId
        Integer userId = (Integer) SessionManager.getSessionValue("userId");

        System.out.println("Logged in user ID: " + userId);  // Debug print

        if (userId == null) {
            // If user_id is not set, show a message asking the user to log in
            javax.swing.JOptionPane.showMessageDialog(this, "Please log in to take the quiz.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Exit the method if the user is not logged in
        }

        int quizId = 8; // Assume this is the quiz ID

        if (hasUserTakenQuiz(quizId)) {
            // If the user has already taken the quiz, exit the method
            return;
        }

        // Open quiz window
        Quiz_18 quizFrame = new Quiz_18(quizId);
        quizFrame.setVisible(true);
        quizFrame.pack();
        quizFrame.setLocationRelativeTo(null);

        // Dispose of current frame
        JFrame parentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentFrame != null) {
            parentFrame.dispose();
        }
    }//GEN-LAST:event_takequizActionPerformed
    public void loginUser(int userId) {
    SessionManager.setSessionValue("userId", userId);  // Use "userId" to store the session
    System.out.println("User ID set in session: " + userId);
}

private boolean hasUserTakenQuiz(int quizId) {
    Integer userId = (Integer) SessionManager.getSessionValue("userId");  // Use "userId"
    if (userId == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please log in to take the quiz.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return true; // Prevent quiz if not logged in
    }

    String query = "SELECT COUNT(*) FROM responses WHERE user_id = ? AND quiz_id = ?";
    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/users-database", "root", "");
         PreparedStatement stmt = conn.prepareStatement(query)) {

        stmt.setInt(1, userId);
        stmt.setInt(2, quizId);
        ResultSet rs = stmt.executeQuery();

        if (rs.next() && rs.getInt(1) > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "You have already taken this quiz.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return true; // User has already taken the quiz
        }

    } catch (SQLException e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    return false; // User can take the quiz
}
    public static void main(String[] args) {
      
        // Create a JFrame
        JFrame frame = new JFrame();

        // Set the frame undecorated
        frame.setUndecorated(true);

        // Add the LESSON_14 JPanel to the frame
        LESSON_18 lessonPanel = new LESSON_18();
        frame.add(lessonPanel);

        // Set frame size and location
        frame.setSize(1200, 800); // Make the frame larger
        frame.setLocationRelativeTo(null); // Center the frame on the screen

        // Add a close button (optional, since no title bar is available)
        JButton closeButton = new JButton("Close");
        closeButton.setBounds(1100, 10, 80, 30); // Position it near the top-right
        lessonPanel.setLayout(null); // Use null layout for custom positioning
        lessonPanel.add(closeButton);

        closeButton.addActionListener(e -> System.exit(0)); // Close the application

        // Set frame visibility
        frame.setVisible(true);

        // Ensure the application exits when the frame is closed
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JButton takequiz;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void pack() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
