/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lesson_panel;

import com.raven.form.SessionManager;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author intsi
 */
public class LESSON_14 extends javax.swing.JPanel {

    /**
     * Creates new form LESSON_13
     */
    public LESSON_14() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea13 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea14 = new javax.swing.JTextArea();
        takequiz = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setText("11–20\n11: 十一 (shí yī) – eleven\n12: 十二 (shí èr) – twelve\n13: 十三 (shí sān) – thirteen\n14: 十四 (shí sì) – fourteen\n15: 十五 (shí wǔ) – fifteen\n16: 十六 (shí liù) – sixteen\n17: 十七 (shí qī) – seventeen\n18: 十八 (shí bā) – eighteen\n19: 十九 (shí jiǔ) – nineteen\n20: 二十 (èr shí) – twenty");
        jScrollPane5.setViewportView(jTextArea5);

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jTextArea6.setText("1–10\n1: 一 (yī) – one\n2: 二 (èr) – two\n3: 三 (sān) – three\n4: 四 (sì) – four\n5: 五 (wǔ) – five\n6: 六 (liù) – six\n7: 七 (qī) – seven\n8: 八 (bā) – eight\n9: 九 (jiǔ) – nine\n10: 十 (shí) – ten");
        jScrollPane6.setViewportView(jTextArea6);

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jTextArea7.setText("31–40\n31: 三十一 (sān shí yī) – thirty-one\n32: 三十二 (sān shí èr) – thirty-two\n33: 三十三 (sān shí sān) – thirty-three\n34: 三十四 (sān shí sì) – thirty-four\n35: 三十五 (sān shí wǔ) – thirty-five\n36: 三十六 (sān shí liù) – thirty-six\n37: 三十七 (sān shí qī) – thirty-seven\n38: 三十八 (sān shí bā) – thirty-eight\n39: 三十九 (sān shí jiǔ) – thirty-nine\n40: 四十 (sì shí) – forty\n");
        jTextArea7.setPreferredSize(new java.awt.Dimension(232, 180));
        jScrollPane7.setViewportView(jTextArea7);

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jTextArea8.setText("\n41–50\n41: 四十一 (sì shí yī) – forty-one\n42: 四十二 (sì shí èr) – forty-two\n43: 四十三 (sì shí sān) – forty-three\n44: 四十四 (sì shí sì) – forty-four\n45: 四十五 (sì shí wǔ) – forty-five\n46: 四十六 (sì shí liù) – forty-six\n47: 四十七 (sì shí qī) – forty-seven\n48: 四十八 (sì shí bā) – forty-eight\n49: 四十九 (sì shí jiǔ) – forty-nine\n50: 五十 (wǔ shí) – fifty\n");
        jTextArea8.setPreferredSize(new java.awt.Dimension(232, 180));
        jScrollPane8.setViewportView(jTextArea8);

        jTextArea9.setColumns(20);
        jTextArea9.setRows(5);
        jTextArea9.setText("21–30\n21: 二十一 (èr shí yī) – twenty-one\n22: 二十二 (èr shí èr) – twenty-two\n23: 二十三 (èr shí sān) – twenty-three\n24: 二十四 (èr shí sì) – twenty-four\n25: 二十五 (èr shí wǔ) – twenty-five\n26: 二十六 (èr shí liù) – twenty-six\n27: 二十七 (èr shí qī) – twenty-seven\n28: 二十八 (èr shí bā) – twenty-eight\n29: 二十九 (èr shí jiǔ) – twenty-nine\n30: 三十 (sān shí) – thirty");
        jScrollPane9.setViewportView(jTextArea9);

        jTextArea10.setColumns(20);
        jTextArea10.setRows(5);
        jTextArea10.setText("\n91–100\n91: 九十一 (jiǔ shí yī) – ninety-one\n92: 九十二 (jiǔ shí èr) – ninety-two\n93: 九十三 (jiǔ shí sān) – ninety-three\n94: 九十四 (jiǔ shí sì) – ninety-four\n95: 九十五 (jiǔ shí wǔ) – ninety-five\n96: 九十六 (jiǔ shí liù) – ninety-six\n97: 九十七 (jiǔ shí qī) – ninety-seven\n98: 九十八 (jiǔ shí bā) – ninety-eight\n99: 九十九 (jiǔ shí jiǔ) – ninety-nine\n100: 一百 (yī bǎi) – one hundred\n");
        jTextArea10.setPreferredSize(new java.awt.Dimension(232, 180));
        jScrollPane10.setViewportView(jTextArea10);

        jTextArea11.setColumns(20);
        jTextArea11.setRows(5);
        jTextArea11.setText("\n71–80\n71: 七十一 (qī shí yī) – seventy-one\n72: 七十二 (qī shí èr) – seventy-two\n73: 七十三 (qī shí sān) – seventy-three\n74: 七十四 (qī shí sì) – seventy-four\n75: 七十五 (qī shí wǔ) – seventy-five\n76: 七十六 (qī shí liù) – seventy-six\n77: 七十七 (qī shí qī) – seventy-seven\n78: 七十八 (qī shí bā) – seventy-eight\n79: 七十九 (qī shí jiǔ) – seventy-nine\n80: 八十 (bā shí) – eighty\n");
        jTextArea11.setPreferredSize(new java.awt.Dimension(232, 180));
        jScrollPane11.setViewportView(jTextArea11);

        jTextArea12.setColumns(20);
        jTextArea12.setRows(5);
        jTextArea12.setText("\n51–60\n51: 五十一 (wǔ shí yī) – fifty-one\n52: 五十二 (wǔ shí èr) – fifty-two\n53: 五十三 (wǔ shí sān) – fifty-three\n54: 五十四 (wǔ shí sì) – fifty-four\n55: 五十五 (wǔ shí wǔ) – fifty-five\n56: 五十六 (wǔ shí liù) – fifty-six\n57: 五十七 (wǔ shí qī) – fifty-seven\n58: 五十八 (wǔ shí bā) – fifty-eight\n59: 五十九 (wǔ shí jiǔ) – fifty-nine\n60: 六十 (liù shí) – sixty");
        jScrollPane12.setViewportView(jTextArea12);

        jTextArea13.setColumns(20);
        jTextArea13.setRows(5);
        jTextArea13.setText("\n61–70\n61: 六十一 (liù shí yī) – sixty-one\n62: 六十二 (liù shí èr) – sixty-two\n63: 六十三 (liù shí sān) – sixty-three\n64: 六十四 (liù shí sì) – sixty-four\n65: 六十五 (liù shí wǔ) – sixty-five\n66: 六十六 (liù shí liù) – sixty-six\n67: 六十七 (liù shí qī) – sixty-seven\n68: 六十八 (liù shí bā) – sixty-eight\n69: 六十九 (liù shí jiǔ) – sixty-nine\n70: 七十 (qī shí) – seventy\n");
        jTextArea13.setPreferredSize(new java.awt.Dimension(232, 180));
        jScrollPane13.setViewportView(jTextArea13);

        jTextArea14.setColumns(20);
        jTextArea14.setRows(5);
        jTextArea14.setText("\n81–90\n81: 八十一 (bā shí yī) – eighty-one\n82: 八十二 (bā shí èr) – eighty-two\n83: 八十三 (bā shí sān) – eighty-three\n84: 八十四 (bā shí sì) – eighty-four\n85: 八十五 (bā shí wǔ) – eighty-five\n86: 八十六 (bā shí liù) – eighty-six\n87: 八十七 (bā shí qī) – eighty-seven\n88: 八十八 (bā shí bā) – eighty-eight\n89: 八十九 (bā shí jiǔ) – eighty-nine\n90: 九十 (jiǔ shí) – ninety\n");
        jTextArea14.setPreferredSize(new java.awt.Dimension(232, 180));
        jScrollPane14.setViewportView(jTextArea14);

        takequiz.setText("Take Quiz");
        takequiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takequizActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel1.setText("CHINESE COUNTINGS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(951, 951, 951)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6)
                            .addComponent(jScrollPane14)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                    .addComponent(jScrollPane9))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                    .addComponent(jScrollPane11)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(takequiz, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(takequiz, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(117, 117, 117)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void takequizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takequizActionPerformed
        // Check if the user is logged in by verifying the session for a valid userId
        Integer userId = (Integer) SessionManager.getSessionValue("userId");

        System.out.println("Logged in user ID: " + userId);  // Debug print

        if (userId == null) {
            // If user_id is not set, show a message asking the user to log in
            javax.swing.JOptionPane.showMessageDialog(this, "Please log in to take the quiz.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Exit the method if the user is not logged in
        }

        int quizId = 4; // Assume this is the quiz ID

        if (hasUserTakenQuiz(quizId)) {
            // If the user has already taken the quiz, exit the method
            return;
        }

        // Open quiz window
        Quiz_14 quizFrame = new Quiz_14(quizId);
        quizFrame.setVisible(true);
        quizFrame.pack();
        quizFrame.setLocationRelativeTo(null);

        // Dispose of current frame
        JFrame parentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentFrame != null) {
            parentFrame.dispose();
        }
    }//GEN-LAST:event_takequizActionPerformed
    public void loginUser(int userId) {
    SessionManager.setSessionValue("userId", userId);  // Use "userId" to store the session
    System.out.println("User ID set in session: " + userId);
}

private boolean hasUserTakenQuiz(int quizId) {
    Integer userId = (Integer) SessionManager.getSessionValue("userId");  // Use "userId"
    if (userId == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please log in to take the quiz.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return true; // Prevent quiz if not logged in
    }

    String query = "SELECT COUNT(*) FROM responses WHERE user_id = ? AND quiz_id = ?";
    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/users-database", "root", "");
         PreparedStatement stmt = conn.prepareStatement(query)) {

        stmt.setInt(1, userId);
        stmt.setInt(2, quizId);
        ResultSet rs = stmt.executeQuery();

        if (rs.next() && rs.getInt(1) > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "You have already taken this quiz.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return true; // User has already taken the quiz
        }

    } catch (SQLException e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    return false; // User can take the quiz
}
    public static void main(String[] args) {
      
        // Create a JFrame
        JFrame frame = new JFrame();

        // Set the frame undecorated
        frame.setUndecorated(true);

        // Add the LESSON_14 JPanel to the frame
        LESSON_14 lessonPanel = new LESSON_14();
        frame.add(lessonPanel);

        // Set frame size and location
        frame.setSize(1200, 800); // Make the frame larger
        frame.setLocationRelativeTo(null); // Center the frame on the screen

        // Add a close button (optional, since no title bar is available)
        JButton closeButton = new JButton("Close");
        closeButton.setBounds(1100, 10, 80, 30); // Position it near the top-right
        lessonPanel.setLayout(null); // Use null layout for custom positioning
        lessonPanel.add(closeButton);

        closeButton.addActionListener(e -> System.exit(0)); // Close the application

        // Set frame visibility
        frame.setVisible(true);

        // Ensure the application exits when the frame is closed
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea13;
    private javax.swing.JTextArea jTextArea14;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JButton takequiz;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void pack() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
