/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lesson_panel;

import com.raven.form.SessionManager;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author intsi
 */
public class LESSON_15 extends javax.swing.JPanel {

    /**
     * Creates new form LESSON_13
     */
    public LESSON_15() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        takequiz = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jTextArea6.setRows(5);
        jTextArea6.setText("6. Negation with 不 (bù) and 没 (méi)\nUse 不 for negating general actions and 没 for past actions.\n\nExample:\n我不吃肉 (Wǒ bù chī ròu) = \"I don’t eat meat.\"\n我没吃饭 (Wǒ méi chī fàn) = \"I didn’t eat.\"\n7. Adjectives as Verbs\nAdjectives can act like verbs to describe a subject.\n\nExample: 他很高 (Tā hěn gāo) = \"He is tall.\"\n8. Particles Indicating Completion (了 / le)\nThe particle 了 is used to indicate a completed action.\n\nExample: 我吃了 (Wǒ chī le) = \"I ate.\"\n9. Using 的 (de) for Possession and Description\nUse 的 to indicate possession or link an adjective to a noun.\n\nExample:\n我的书 (Wǒ de shū) = \"My book.\"\n漂亮的花 (Piàoliàng de huā) = \"Beautiful flowers.\"\n10. Questions with Question Words\nUse question words like 什么 (shénme, \"what\") or 谁 (shéi, \"who\") for open-ended questions.\n\nExample:\n这是什么？(Zhè shì shénme?) = \"What is this?\"\n他是谁？(Tā shì shéi?) = \"Who is he?\"");
        jScrollPane6.setViewportView(jTextArea6);

        takequiz.setText("Take Quiz");
        takequiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takequizActionPerformed(evt);
            }
        });

        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jTextArea7.setRows(5);
        jTextArea7.setText("1. Subject + Verb + Object (SVO)\nThe standard sentence structure is simple.\n\nExample: 我喝水 (Wǒ hē shuǐ) = \"I drink water.\"\n2. No Verb Conjugations\nVerbs do not change form for tense or subject. Time is indicated with words or context.\n\nExample:\n我去 (Wǒ qù) = \"I go.\"\n我昨天去 (Wǒ zuótiān qù) = \"I went yesterday.\"\n3. Time Words Before Verbs\nTime expressions typically appear before the verb.\n\nExample: 我明天去学校 (Wǒ míngtiān qù xuéxiào) = \"I will go to school tomorrow.\"\n4. Measure Words (量词 / Liàngcí)\nNouns require measure words when used with numbers or demonstratives.\n\nExample: 一只猫 (Yī zhī māo) = \"One cat.\"\n5. Questions with 吗 (ma)\nTo form yes/no questions, add 吗 at the end of a statement.\n\nExample: 你喜欢中国吗？(Nǐ xǐhuān Zhōngguó ma?) = \"Do you like China?\"\n");
        jScrollPane7.setViewportView(jTextArea7);

        jLabel1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel1.setText("CHINESE GRAMMARS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1)
                        .addGap(814, 814, 814)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(644, 644, 644)
                        .addComponent(takequiz, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(takequiz, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(800, 800, 800))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void takequizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takequizActionPerformed
        // Check if the user is logged in by verifying the session for a valid userId
        Integer userId = (Integer) SessionManager.getSessionValue("userId");

        System.out.println("Logged in user ID: " + userId);  // Debug print

        if (userId == null) {
            // If user_id is not set, show a message asking the user to log in
            javax.swing.JOptionPane.showMessageDialog(this, "Please log in to take the quiz.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Exit the method if the user is not logged in
        }

        int quizId = 5; // Assume this is the quiz ID

        if (hasUserTakenQuiz(quizId)) {
            // If the user has already taken the quiz, exit the method
            return;
        }

        // Open quiz window
        Quiz_15 quizFrame = new Quiz_15(quizId);
        quizFrame.setVisible(true);
        quizFrame.pack();
        quizFrame.setLocationRelativeTo(null);

        // Dispose of current frame
        JFrame parentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentFrame != null) {
            parentFrame.dispose();
        }
    }//GEN-LAST:event_takequizActionPerformed
    public void loginUser(int userId) {
    SessionManager.setSessionValue("userId", userId);  // Use "userId" to store the session
    System.out.println("User ID set in session: " + userId);
}

private boolean hasUserTakenQuiz(int quizId) {
    Integer userId = (Integer) SessionManager.getSessionValue("userId");  // Use "userId"
    if (userId == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please log in to take the quiz.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return true; // Prevent quiz if not logged in
    }

    String query = "SELECT COUNT(*) FROM responses WHERE user_id = ? AND quiz_id = ?";
    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/users-database", "root", "");
         PreparedStatement stmt = conn.prepareStatement(query)) {

        stmt.setInt(1, userId);
        stmt.setInt(2, quizId);
        ResultSet rs = stmt.executeQuery();

        if (rs.next() && rs.getInt(1) > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "You have already taken this quiz.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return true; // User has already taken the quiz
        }

    } catch (SQLException e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    return false; // User can take the quiz
}
    public static void main(String[] args) {
      
        // Create a JFrame
        JFrame frame = new JFrame();

        // Set the frame undecorated
        frame.setUndecorated(true);

        // Add the LESSON_14 JPanel to the frame
        LESSON_15 lessonPanel = new LESSON_15();
        frame.add(lessonPanel);

        // Set frame size and location
        frame.setSize(1200, 800); // Make the frame larger
        frame.setLocationRelativeTo(null); // Center the frame on the screen

        // Add a close button (optional, since no title bar is available)
        JButton closeButton = new JButton("Close");
        closeButton.setBounds(1100, 10, 80, 30); // Position it near the top-right
        lessonPanel.setLayout(null); // Use null layout for custom positioning
        lessonPanel.add(closeButton);

        closeButton.addActionListener(e -> System.exit(0)); // Close the application

        // Set frame visibility
        frame.setVisible(true);

        // Ensure the application exits when the frame is closed
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JButton takequiz;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void pack() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
