/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lesson_panel;

import com.raven.form.SessionManager;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author intsi
 */
public class LESSON_17 extends javax.swing.JPanel {

    /**
     * Creates new form LESSON_13
     */
    public LESSON_17() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        takequiz = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/Screenshot 2024-12-16 033259.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/Screenshot 2024-12-16 033317.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel3.setText("JAPANESE ALPHABET");

        jLabel4.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel4.setText("HIRAGANA");

        takequiz.setText("Take Quiz");
        takequiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takequizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(148, 148, 148)
                                        .addComponent(takequiz, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(2516, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(takequiz, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(714, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void takequizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takequizActionPerformed
        // Check if the user is logged in by verifying the session for a valid userId
        Integer userId = (Integer) SessionManager.getSessionValue("userId");

        System.out.println("Logged in user ID: " + userId);  // Debug print

        if (userId == null) {
            // If user_id is not set, show a message asking the user to log in
            javax.swing.JOptionPane.showMessageDialog(this, "Please log in to take the quiz.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Exit the method if the user is not logged in
        }

        int quizId = 7; // Assume this is the quiz ID

        if (hasUserTakenQuiz(quizId)) {
            // If the user has already taken the quiz, exit the method
            return;
        }

        // Open quiz window
        Quiz_17 quizFrame = new Quiz_17(quizId);
        quizFrame.setVisible(true);
        quizFrame.pack();
        quizFrame.setLocationRelativeTo(null);

        // Dispose of current frame
        JFrame parentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentFrame != null) {
            parentFrame.dispose();
        }
    }//GEN-LAST:event_takequizActionPerformed
    public void loginUser(int userId) {
    SessionManager.setSessionValue("userId", userId);  // Use "userId" to store the session
    System.out.println("User ID set in session: " + userId);
}

private boolean hasUserTakenQuiz(int quizId) {
    Integer userId = (Integer) SessionManager.getSessionValue("userId");  // Use "userId"
    if (userId == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please log in to take the quiz.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return true; // Prevent quiz if not logged in
    }

    String query = "SELECT COUNT(*) FROM responses WHERE user_id = ? AND quiz_id = ?";
    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/users-database", "root", "");
         PreparedStatement stmt = conn.prepareStatement(query)) {

        stmt.setInt(1, userId);
        stmt.setInt(2, quizId);
        ResultSet rs = stmt.executeQuery();

        if (rs.next() && rs.getInt(1) > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "You have already taken this quiz.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return true; // User has already taken the quiz
        }

    } catch (SQLException e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    return false; // User can take the quiz
}
    public static void main(String[] args) {
      
        // Create a JFrame
        JFrame frame = new JFrame();

        // Set the frame undecorated
        frame.setUndecorated(true);

        // Add the LESSON_14 JPanel to the frame
        LESSON_17 lessonPanel = new LESSON_17();
        frame.add(lessonPanel);

        // Set frame size and location
        frame.setSize(1200, 800); // Make the frame larger
        frame.setLocationRelativeTo(null); // Center the frame on the screen

        // Add a close button (optional, since no title bar is available)
        JButton closeButton = new JButton("Close");
        closeButton.setBounds(1100, 10, 80, 30); // Position it near the top-right
        lessonPanel.setLayout(null); // Use null layout for custom positioning
        lessonPanel.add(closeButton);

        closeButton.addActionListener(e -> System.exit(0)); // Close the application

        // Set frame visibility
        frame.setVisible(true);

        // Ensure the application exits when the frame is closed
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton takequiz;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void pack() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
