/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lesson_panel;

import com.raven.form.Form_Home;
import com.raven.form.SessionManager;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author intsi
 */
public class Quiz_16 extends javax.swing.JFrame {

    /**
     * Creates new form Quiz_16
     */
    private int quiz_id;  // Add a quiz_id field

    public Quiz_16(int quiz_id) {  // Modify the constructor to accept quiz_id
        this.quiz_id = quiz_id;  // Store the quiz_id in the class
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Radio5B = new javax.swing.JRadioButton();
        Radio5C = new javax.swing.JRadioButton();
        Radio1B = new javax.swing.JRadioButton();
        Radio5D = new javax.swing.JRadioButton();
        Radio1C = new javax.swing.JRadioButton();
        Submit = new javax.swing.JButton();
        Radio1D = new javax.swing.JRadioButton();
        Back = new javax.swing.JButton();
        Question2 = new javax.swing.JLabel();
        Radio2A = new javax.swing.JRadioButton();
        Radio2B = new javax.swing.JRadioButton();
        Radio2C = new javax.swing.JRadioButton();
        Radio2D = new javax.swing.JRadioButton();
        Question3 = new javax.swing.JLabel();
        Radio3A = new javax.swing.JRadioButton();
        Radio3B = new javax.swing.JRadioButton();
        Radio3C = new javax.swing.JRadioButton();
        Radio3D = new javax.swing.JRadioButton();
        Question4 = new javax.swing.JLabel();
        Radio4A = new javax.swing.JRadioButton();
        Radio4B = new javax.swing.JRadioButton();
        Radio4C = new javax.swing.JRadioButton();
        Radio4D = new javax.swing.JRadioButton();
        Question5 = new javax.swing.JLabel();
        Radio5A = new javax.swing.JRadioButton();
        Question1 = new javax.swing.JLabel();
        Radio1A = new javax.swing.JRadioButton();
        Question6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Radio5B.setText("B) Because it is easy to learn (学ぶのが簡単だから)");

        Radio5C.setText("C) Due to its widespread use in other countries (他の国々で広く使われているから)");
        Radio5C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio5CActionPerformed(evt);
            }
        });

        Radio1B.setText("B) Mandarin (普通話)");
        Radio1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio1BActionPerformed(evt);
            }
        });

        Radio5D.setText("D) Because it is similar to Chinese (中国語に似ているから)");

        Radio1C.setText("C) Japanese (日本語)");
        Radio1C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio1CActionPerformed(evt);
            }
        });

        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Radio1D.setText("D) Cantonese (広東");

        Back.setText("BACK");
        Back.setBorderPainted(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Question2.setText("2. Which writing system is used to represent the phonetic aspects of Japanese? ");

        Radio2A.setText("A) Kanji (漢字)");

        Radio2B.setText("B) Hiragana and Katakana (ひらがなとカタカナ)");

        Radio2C.setText("\tC) Hangul (ハングル)");

        Radio2D.setText("D) Cyrillic (キリル文字)");

        Question3.setText("Which language family does Japanese belong to? 日本語はどの言語系統に属していますか？");

        Radio3A.setText("A) Indo-European (インド・ヨーロッパ語族)");

        Radio3B.setText("B) Japonic (ジャポニック語族)");

        Radio3C.setText("C) Sino-Tibetan (漢藏語族)");
        Radio3C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio3CActionPerformed(evt);
            }
        });

        Radio3D.setText("D) Afro-Asiatic (アフロ・アジア語族)");

        Question4.setText("4. Which dialect of Japanese is used as the standard in media, education, and government? メディア、教育、政府で使われる標準的な日本語の方言はどれですか？");

        Radio4A.setText("A) Kansai dialect (関西弁)");

        Radio4B.setText("B) Kyoto dialect (京都弁)");

        Radio4C.setText("C) Tokyo dialect (東京弁)");

        Radio4D.setText("D) Okinawan dialect (沖縄方言)");
        Radio4D.setBorderPainted(true);

        Question5.setText("5. Why is Japanese increasingly learned as a foreign language? なぜ日本語は外国語として学ばれることが増えているのでしょうか？ ");

        Radio5A.setText("A) Due to Japan’s cultural influence in technology, business, and entertainment (日本の技術、ビジネス、エンターテイメントの文化的影響のため)");

        Question1.setText("1. What is the official language of Japan? 日本の公用語は何ですか？ •\t");

        Radio1A.setText("\tA) Korean (韓国語)");
        Radio1A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio1AActionPerformed(evt);
            }
        });

        Question6.setText("日本語の音を表現するために使用される文字体系はどれですか？");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Question2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Question3, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(519, 519, 519)
                                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Radio3A)
                            .addComponent(Radio3B)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Radio3D)
                                    .addComponent(Radio3C))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Radio1A)
                            .addComponent(Radio1B)
                            .addComponent(Radio1C)
                            .addComponent(Radio1D)
                            .addComponent(Question6, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Radio2C)
                            .addComponent(Radio2D))
                        .addGap(1650, 2093, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Radio2A)
                            .addComponent(Radio2B))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Question1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Question4)
                            .addComponent(Radio4A)
                            .addComponent(Radio4B)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Radio5A)
                            .addComponent(Question5, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Radio4D)
                            .addComponent(Radio4C)
                            .addComponent(Radio5B)
                            .addComponent(Radio5C)
                            .addComponent(Radio5D))
                        .addGap(71, 71, 71)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(Question1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(Radio1A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Radio1B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Radio1C)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Radio1D))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(Question4)
                        .addGap(54, 54, 54)
                        .addComponent(Radio4A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Radio4B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Radio4C)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Radio4D)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Question2)
                        .addGap(12, 12, 12)
                        .addComponent(Question6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Question5)
                        .addGap(25, 25, 25)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Radio2A)
                    .addComponent(Radio5A))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Radio2B)
                    .addComponent(Radio5B))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Radio2C))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Radio5C)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Radio2D)
                    .addComponent(Radio5D))
                .addGap(49, 49, 49)
                .addComponent(Question3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Radio3A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Radio3B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Radio3C)
                .addGap(18, 18, 18)
                .addComponent(Radio3D)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
            private int getLoggedInUserId() {
        // Mock session management. Replace this with the actual session handling logic
        Map<String, Object> session = SessionManager.getSession(); // Example session manager
        if (session.containsKey("userId")) {
            return (int) session.get("userId");
        } else {
            JOptionPane.showMessageDialog(this, "No user logged in. Please log in and try again.", "Error", JOptionPane.ERROR_MESSAGE);
            return -1; // Indicate no user is logged in
        }
    }
    private void saveResponseToDatabase(int userId, int score, int quizId) {
        String url = "jdbc:mysql://localhost:3306/users-database"; // Ensure correct database URL
        String username = "root";
        String password = ""; // Keep it empty if no password is set

        String query = "INSERT INTO responses (response, user_id, quiz_id, lesson_id) VALUES (?, ?, ?, ?)";

        try (Connection conn = DriverManager.getConnection(url, username, password);
             PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setInt(1, score); // Set the response (score)
            stmt.setInt(2, userId); // Set the user ID
            stmt.setInt(3, quizId);  // Set the quiz ID
            stmt.setInt(4, 6);

            stmt.executeUpdate(); // Execute the query
            System.out.println("Response saved to the database.");

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to save response to the database.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void Radio1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio1BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio1BActionPerformed

    private void Radio1CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio1CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio1CActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
    // Validate that each question has a selected answer
    if (!Radio1A.isSelected() && !Radio1B.isSelected() && !Radio1C.isSelected() && !Radio1D.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please select an answer for Question 1.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!Radio2A.isSelected() && !Radio2B.isSelected() && !Radio2C.isSelected() && !Radio2D.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please select an answer for Question 2.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!Radio3A.isSelected() && !Radio3B.isSelected() && !Radio3C.isSelected() && !Radio3D.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please select an answer for Question 3.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!Radio4A.isSelected() && !Radio4B.isSelected() && !Radio4C.isSelected() && !Radio4D.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please select an answer for Question 4.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!Radio5A.isSelected() && !Radio5B.isSelected() && !Radio5C.isSelected() && !Radio5D.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please select an answer for Question 5.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int score = 0;

    // Calculate the score
    if (Radio1C.isSelected()) score++;
    if (Radio2B.isSelected()) score++;
    if (Radio3B.isSelected()) score++;
    if (Radio4C.isSelected()) score++;
    if (Radio5D.isSelected()) score++;

    // Display the score to the user
    JOptionPane.showMessageDialog(this, "Your score: " + score + "/5", "Quiz Result", JOptionPane.INFORMATION_MESSAGE);

    // Retrieve logged-in user ID (Store it in session if not already done)
    int userId = getLoggedInUserId();
    if (userId == -1) {
        return; // Abort if no user is logged in
    }

    // Store the user ID in the session (if not done earlier)
    SessionManager.getSession().put("userId", userId);

    // Save the response to the database
    saveResponseToDatabase(userId, score, quiz_id);

    // Cleanup and redirect to Form_Home
    JOptionPane.showMessageDialog(this, "Thank you for taking the quiz!");
    Form_Home homeForm = new Form_Home();
    homeForm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_SubmitActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        LESSON_16 lesson16 = new LESSON_16();
        lesson16.setVisible(true);

    // Close the current Quiz_11 JFrame
    this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void Radio3CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio3CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio3CActionPerformed

    private void Radio1AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio1AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio1AActionPerformed

    private void Radio5CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio5CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio5CActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz_16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz_16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz_16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz_16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Quiz_16 quiz = new Quiz_16(6);  // Pass quiz_id = 6
            quiz.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Question1;
    private javax.swing.JLabel Question2;
    private javax.swing.JLabel Question3;
    private javax.swing.JLabel Question4;
    private javax.swing.JLabel Question5;
    private javax.swing.JLabel Question6;
    private javax.swing.JRadioButton Radio1A;
    private javax.swing.JRadioButton Radio1B;
    private javax.swing.JRadioButton Radio1C;
    private javax.swing.JRadioButton Radio1D;
    private javax.swing.JRadioButton Radio2A;
    private javax.swing.JRadioButton Radio2B;
    private javax.swing.JRadioButton Radio2C;
    private javax.swing.JRadioButton Radio2D;
    private javax.swing.JRadioButton Radio3A;
    private javax.swing.JRadioButton Radio3B;
    private javax.swing.JRadioButton Radio3C;
    private javax.swing.JRadioButton Radio3D;
    private javax.swing.JRadioButton Radio4A;
    private javax.swing.JRadioButton Radio4B;
    private javax.swing.JRadioButton Radio4C;
    private javax.swing.JRadioButton Radio4D;
    private javax.swing.JRadioButton Radio5A;
    private javax.swing.JRadioButton Radio5B;
    private javax.swing.JRadioButton Radio5C;
    private javax.swing.JRadioButton Radio5D;
    private javax.swing.JButton Submit;
    // End of variables declaration//GEN-END:variables

}