/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lesson_panel;

import com.raven.form.Form_Home;
import com.raven.form.SessionManager;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author intsi
 */
public class Quiz_14 extends javax.swing.JFrame {

    /**
     * Creates new form Quiz_14
     */
    private int quiz_id;  // Add a quiz_id field

    public Quiz_14(int quiz_id) {  // Modify the constructor to accept quiz_id
        this.quiz_id = quiz_id;  // Store the quiz_id in the class
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Radio5B = new javax.swing.JRadioButton();
        Radio5C = new javax.swing.JRadioButton();
        Radio1B = new javax.swing.JRadioButton();
        Radio5D = new javax.swing.JRadioButton();
        Radio1C = new javax.swing.JRadioButton();
        Submit = new javax.swing.JButton();
        Radio1D = new javax.swing.JRadioButton();
        Back = new javax.swing.JButton();
        Question2 = new javax.swing.JLabel();
        Radio2A = new javax.swing.JRadioButton();
        Radio2B = new javax.swing.JRadioButton();
        Radio2C = new javax.swing.JRadioButton();
        Radio2D = new javax.swing.JRadioButton();
        Question3 = new javax.swing.JLabel();
        Radio3A = new javax.swing.JRadioButton();
        Radio3B = new javax.swing.JRadioButton();
        Radio3C = new javax.swing.JRadioButton();
        Radio3D = new javax.swing.JRadioButton();
        Question4 = new javax.swing.JLabel();
        Radio4A = new javax.swing.JRadioButton();
        Radio4B = new javax.swing.JRadioButton();
        Radio4C = new javax.swing.JRadioButton();
        Radio4D = new javax.swing.JRadioButton();
        Question5 = new javax.swing.JLabel();
        Radio5A = new javax.swing.JRadioButton();
        Question1 = new javax.swing.JLabel();
        Radio1A = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Radio5B.setText("B) 45");

        Radio5C.setText("C) 46");

        Radio1B.setText("B) 二十四 (èr shí sì");
        Radio1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio1BActionPerformed(evt);
            }
        });

        Radio5D.setText("D) 47");

        Radio1C.setText("C) 二十六 (èr shí liù)");
        Radio1C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio1CActionPerformed(evt);
            }
        });

        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Radio1D.setText("D) 二十七 (èr shí qī)");

        Back.setText("BACK");
        Back.setBorderPainted(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Question2.setText("2.  \"三十八\" 是哪个数字？ (What number is \"三十八 (sān shí bā)\"?)");

        Radio2A.setText("A) 28");

        Radio2B.setText("B) 38");

        Radio2C.setText("C) 48");
        Radio2C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio2CActionPerformed(evt);
            }
        });

        Radio2D.setText("D) 58");

        Question3.setText("3.哪个是 \"91\" 的正确翻译？ (Which is the correct translation for \"91\"?)");

        Radio3A.setText("A) 九十一 (jiǔ shí yī)");

        Radio3B.setText("B) 九十二 (jiǔ shí èr)");

        Radio3C.setText("C) 八十一 (bā shí yī)");
        Radio3C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio3CActionPerformed(evt);
            }
        });

        Radio3D.setText("D) 九十 (jiǔ shí)");

        Question4.setText("4. 数字 \"70\" 的拼音是什么？ (What is the Pinyin for the number \"70\"?)");

        Radio4A.setText("A) liù shí");

        Radio4B.setText("B) qī shí");

        Radio4C.setText("C) bā shí");

        Radio4D.setText("D) jiǔ shí");
        Radio4D.setBorderPainted(true);

        Question5.setText(" \"四十五\" 是什么数字？ (What number is \"四十五 (sì shí wǔ)\"?)");

        Radio5A.setText("A) 44");

        Question1.setText(" 1. 数字 \"25\" 用中文怎么说？ ( How do you say the number \"25\" in Chinese?)");

        Radio1A.setText("A) 二十五 (èr shí wǔ)");
        Radio1A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio1AActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Question3, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Question1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Radio1A)
                            .addComponent(Radio1B)
                            .addComponent(Radio1C)
                            .addComponent(Radio1D))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Question4, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Radio4A)
                            .addComponent(Radio4B)
                            .addComponent(Radio4C)
                            .addComponent(Radio4D)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Question2, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Radio2B, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Radio2A, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(Radio2C)
                            .addComponent(Radio2D))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Question5, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Radio5A)
                            .addComponent(Radio5B)
                            .addComponent(Radio5C)
                            .addComponent(Radio5D)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(Radio3A)
                    .addComponent(Radio3B)
                    .addComponent(Radio3C)
                    .addComponent(Radio3D))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Question1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Radio1A))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Question4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Radio4A)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Radio1B)
                    .addComponent(Radio4B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Radio1C)
                    .addComponent(Radio4C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Radio1D)
                    .addComponent(Radio4D))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Question2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Radio2A))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Question5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Radio5A)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Radio2B)
                    .addComponent(Radio5B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Radio2C)
                    .addComponent(Radio5C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Radio2D)
                    .addComponent(Radio5D))
                .addGap(18, 18, 18)
                .addComponent(Question3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Radio3A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Radio3B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Radio3C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Radio3D)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
            private int getLoggedInUserId() {
        // Mock session management. Replace this with the actual session handling logic
        Map<String, Object> session = SessionManager.getSession(); // Example session manager
        if (session.containsKey("userId")) {
            return (int) session.get("userId");
        } else {
            JOptionPane.showMessageDialog(this, "No user logged in. Please log in and try again.", "Error", JOptionPane.ERROR_MESSAGE);
            return -1; // Indicate no user is logged in
        }
    }
    private void saveResponseToDatabase(int userId, int score, int quizId) {
        String url = "jdbc:mysql://localhost:3306/users-database"; // Ensure correct database URL
        String username = "root";
        String password = ""; // Keep it empty if no password is set

        String query = "INSERT INTO responses (response, user_id, quiz_id, lesson_id) VALUES (?, ?, ?, ?)";

        try (Connection conn = DriverManager.getConnection(url, username, password);
             PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setInt(1, score); // Set the response (score)
            stmt.setInt(2, userId); // Set the user ID
            stmt.setInt(3, quizId);  // Set the quiz ID
            stmt.setInt(4, 4);

            stmt.executeUpdate(); // Execute the query
            System.out.println("Response saved to the database.");

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to save response to the database.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void Radio1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio1BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio1BActionPerformed

    private void Radio1CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio1CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio1CActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
    // Validate that each question has a selected answer
    if (!Radio1A.isSelected() && !Radio1B.isSelected() && !Radio1C.isSelected() && !Radio1D.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please select an answer for Question 1.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!Radio2A.isSelected() && !Radio2B.isSelected() && !Radio2C.isSelected() && !Radio2D.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please select an answer for Question 2.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!Radio3A.isSelected() && !Radio3B.isSelected() && !Radio3C.isSelected() && !Radio3D.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please select an answer for Question 3.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!Radio4A.isSelected() && !Radio4B.isSelected() && !Radio4C.isSelected() && !Radio4D.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please select an answer for Question 4.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!Radio5A.isSelected() && !Radio5B.isSelected() && !Radio5C.isSelected() && !Radio5D.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please select an answer for Question 5.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int score = 0;

    // Calculate the score
    if (Radio1A.isSelected()) score++;
    if (Radio2B.isSelected()) score++;
    if (Radio3A.isSelected()) score++;
    if (Radio4B.isSelected()) score++;
    if (Radio5B.isSelected()) score++;

    // Display the score to the user
    JOptionPane.showMessageDialog(this, "Your score: " + score + "/5", "Quiz Result", JOptionPane.INFORMATION_MESSAGE);

    // Retrieve logged-in user ID (Store it in session if not already done)
    int userId = getLoggedInUserId();
    if (userId == -1) {
        return; // Abort if no user is logged in
    }

    // Store the user ID in the session (if not done earlier)
    SessionManager.getSession().put("userId", userId);

    // Save the response to the database
    saveResponseToDatabase(userId, score, quiz_id);

    // Cleanup and redirect to Form_Home
    JOptionPane.showMessageDialog(this, "Thank you for taking the quiz!");
    Form_Home homeForm = new Form_Home();
    homeForm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_SubmitActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        LESSON_14 lesson14 = new LESSON_14();
        lesson14.setVisible(true);

        // Close the current Quiz_11 JFrame
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void Radio3CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio3CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio3CActionPerformed

    private void Radio1AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio1AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio1AActionPerformed

    private void Radio2CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio2CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio2CActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz_14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz_14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz_14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz_14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(() -> {
            Quiz_14 quiz = new Quiz_14(4);  // Pass quiz_id = 4
            quiz.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Question1;
    private javax.swing.JLabel Question2;
    private javax.swing.JLabel Question3;
    private javax.swing.JLabel Question4;
    private javax.swing.JLabel Question5;
    private javax.swing.JRadioButton Radio1A;
    private javax.swing.JRadioButton Radio1B;
    private javax.swing.JRadioButton Radio1C;
    private javax.swing.JRadioButton Radio1D;
    private javax.swing.JRadioButton Radio2A;
    private javax.swing.JRadioButton Radio2B;
    private javax.swing.JRadioButton Radio2C;
    private javax.swing.JRadioButton Radio2D;
    private javax.swing.JRadioButton Radio3A;
    private javax.swing.JRadioButton Radio3B;
    private javax.swing.JRadioButton Radio3C;
    private javax.swing.JRadioButton Radio3D;
    private javax.swing.JRadioButton Radio4A;
    private javax.swing.JRadioButton Radio4B;
    private javax.swing.JRadioButton Radio4C;
    private javax.swing.JRadioButton Radio4D;
    private javax.swing.JRadioButton Radio5A;
    private javax.swing.JRadioButton Radio5B;
    private javax.swing.JRadioButton Radio5C;
    private javax.swing.JRadioButton Radio5D;
    private javax.swing.JButton Submit;
    // End of variables declaration//GEN-END:variables

    private void saveResponseToDatabase(int userId, int score) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
