/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lesson_panel;

import com.raven.component.Menu;
import com.raven.form.Form_Home;
import com.raven.form.SessionManager;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author intsi
 */
public class Quiz_11 extends javax.swing.JFrame {
    
    private int quiz_id;  // Add a quiz_id field

    public Quiz_11(int quiz_id) {  // Modify the constructor to accept quiz_id
        this.quiz_id = quiz_id;  // Store the quiz_id in the class
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG1 = new javax.swing.ButtonGroup();
        BG2 = new javax.swing.ButtonGroup();
        BG3 = new javax.swing.ButtonGroup();
        BG4 = new javax.swing.ButtonGroup();
        BG5 = new javax.swing.ButtonGroup();
        Question1 = new javax.swing.JLabel();
        Radio1A = new javax.swing.JRadioButton();
        Radio1B = new javax.swing.JRadioButton();
        Radio1C = new javax.swing.JRadioButton();
        Radio1D = new javax.swing.JRadioButton();
        Question2 = new javax.swing.JLabel();
        Radio2A = new javax.swing.JRadioButton();
        Radio2B = new javax.swing.JRadioButton();
        Radio2C = new javax.swing.JRadioButton();
        Radio2D = new javax.swing.JRadioButton();
        Question3 = new javax.swing.JLabel();
        Radio3A = new javax.swing.JRadioButton();
        Radio3B = new javax.swing.JRadioButton();
        Radio3C = new javax.swing.JRadioButton();
        Radio3D = new javax.swing.JRadioButton();
        Question4 = new javax.swing.JLabel();
        Radio4A = new javax.swing.JRadioButton();
        Radio4B = new javax.swing.JRadioButton();
        Radio4C = new javax.swing.JRadioButton();
        Radio4D = new javax.swing.JRadioButton();
        Question5 = new javax.swing.JLabel();
        Radio5A = new javax.swing.JRadioButton();
        Radio5B = new javax.swing.JRadioButton();
        Radio5C = new javax.swing.JRadioButton();
        Radio5D = new javax.swing.JRadioButton();
        Submit = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Question6 = new javax.swing.JLabel();
        Question7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Question1.setText("1. Mandarin shì zài nǎ yí ge cháodài zuìzǎo bèi jìzǎi de? (In which dynasty was Mandarin first documented?)");

        BG1.add(Radio1A);
        Radio1A.setText("A. Tángcháo (Tang Dynasty)");
        Radio1A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio1AActionPerformed(evt);
            }
        });

        BG1.add(Radio1B);
        Radio1B.setText("B. Yuáncháo (Yuan Dynasty)");
        Radio1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio1BActionPerformed(evt);
            }
        });

        BG1.add(Radio1C);
        Radio1C.setText("C. Míngcháo (Ming Dynasty)");
        Radio1C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio1CActionPerformed(evt);
            }
        });

        BG1.add(Radio1D);
        Radio1D.setText("D. Qīngcháo (Qing Dynasty)");

        Question2.setText("  (Why was Mandarin designated as the official language of China?)");

        BG2.add(Radio2A);
        Radio2A.setText("A. Yīn wéi tā shì zuì jiǔ de yǔyán. (Because it is the oldest language.)");

        BG2.add(Radio2B);
        Radio2B.setText("B. Yīn wéi tā shì běifāng zuì liúxíng de fāngyán. (Because it is the most common northern dialect.)");

        BG2.add(Radio2C);
        Radio2C.setText("C. Yīn wéi tā jiǎndānyì dǒng. (Because it is easy to understand.)");

        BG2.add(Radio2D);
        Radio2D.setText("d) 达罗毗荼语系 Dá Luō Pí Tú yǔxì");

        Question3.setText("3. Chúle Zhōngguó, nǎxiē guójiā yě yǐ Mandarin zuòwéi guānfāng yǔyán? (Besides China, which countries also use Mandarin as an official language?)");

        BG3.add(Radio3A);
        Radio3A.setText("A. Rìběn hé Hánguó (Japan and South Korea)");

        BG3.add(Radio3B);
        Radio3B.setText("B. Táiwān hé Xīnjiāpō (Taiwan and Singapore)");

        BG3.add(Radio3C);
        Radio3C.setText("C. Mǎláixīyà hé Yìndù (Malaysia and India)");
        Radio3C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio3CActionPerformed(evt);
            }
        });

        BG3.add(Radio3D);
        Radio3D.setText("D. Měiguó hé Yīngguó (United States and United Kingdom)");

        Question4.setText("4. Mandarin de cíhuì hé shēngdiào zěnyàng gēnjù dìqū chūxiàn biànhuà? (How do Mandarin's vocabulary and tones vary by region?)");

        BG4.add(Radio4A);
        Radio4A.setText("A. Suíjī de (Randomly) B. Méiyǒu biànhuà (No variation)");

        BG4.add(Radio4B);
        Radio4B.setText("B. Méiyǒu biànhuà (No variation)");

        BG4.add(Radio4C);
        Radio4C.setText("C. Gēnjù dìfāng de chuántǒng hé fāngyán (Based on local traditions and dialects)");

        BG4.add(Radio4D);
        Radio4D.setText("D. Yóu yòngcí láiyuán juédìng (Determined by word origins) ");
        Radio4D.setBorderPainted(true);

        Question5.setText("5. Zhōngguó nánfāng rén tōngcháng yǐ shénme zuòwéi mǔyǔ, tāmen zěnme xuéxí Mandarin?");

        BG5.add(Radio5A);
        Radio5A.setText("A. Zhǔyào shuō qítā de Zhōngwén fāngyán, tōngguò xuéxiào xuéxí Mandarin. (They mainly speak other Chinese dialects and learn Mandarin at school.)");

        BG5.add(Radio5B);
        Radio5B.setText("B. Zhǔyào shuō Yīngyǔ, zìrán xuéhuì Mandarin. (They mainly speak English and naturally learn Mandarin.)");

        BG5.add(Radio5C);
        Radio5C.setText("C. Yòng Běijīng huà zuòwéi mǔyǔ, zhíjiē shuō Mandarin. (They use the Beijing dialect as their mother tongue and directly speak Mandarin.)");

        BG5.add(Radio5D);
        Radio5D.setText("D. Bù xué Mandarin, zhǐ yòng fāngyán. (They don’t learn Mandarin and only use dialects.)");

        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Back.setText("BACK");
        Back.setBorderPainted(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Question6.setText("2. Wèishéme Mandarin bèi dìngwéi Zhōngguó de gōngyòng yǔyán?");

        Question7.setText(" (What do southern Chinese people typically speak as their first language, and how do they learn Mandarin?)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Question6, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Question7, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(415, 415, 415))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addComponent(Question2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1236, 1236, 1236))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Radio2C)
                                    .addComponent(Radio2D)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Radio2B, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Radio2A, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Radio5B)
                                            .addComponent(Radio5A)
                                            .addComponent(Radio5C)
                                            .addComponent(Radio5D))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(Question5, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Radio3A)
                                    .addComponent(Question3, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Question1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Radio1A)
                                            .addComponent(Radio1B)
                                            .addComponent(Radio1C)
                                            .addComponent(Radio1D))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Question4, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Radio4A)
                                            .addComponent(Radio4B)
                                            .addComponent(Radio4C)
                                            .addComponent(Radio4D)))
                                    .addComponent(Radio3C)
                                    .addComponent(Radio3D))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Radio3B)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Question1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Radio1A))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Question4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Radio4A)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Radio1B)
                    .addComponent(Radio4B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Radio1C)
                    .addComponent(Radio4C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Radio1D)
                    .addComponent(Radio4D))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Question6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Question2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(Radio2A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Radio2B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Radio2C)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Radio2D)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(Question5)
                        .addGap(18, 18, 18)
                        .addComponent(Question7)
                        .addGap(12, 12, 12)
                        .addComponent(Radio5A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Radio5B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Radio5C)
                        .addGap(18, 18, 18)
                        .addComponent(Radio5D)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(Question3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Radio3A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Radio3B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Radio3C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Radio3D)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        private int getLoggedInUserId() {
        // Mock session management. Replace this with the actual session handling logic
        Map<String, Object> session = SessionManager.getSession(); // Example session manager
        if (session.containsKey("userId")) {
            return (int) session.get("userId");
        } else {
            JOptionPane.showMessageDialog(this, "No user logged in. Please log in and try again.", "Error", JOptionPane.ERROR_MESSAGE);
            return -1; // Indicate no user is logged in
        }
    }
    private void saveResponseToDatabase(int userId, int score, int quizId) {
        String url = "jdbc:mysql://localhost:3306/users-database"; // Ensure correct database URL
        String username = "root";
        String password = ""; // Keep it empty if no password is set

        String query = "INSERT INTO responses (response, user_id, quiz_id, lesson_id) VALUES (?, ?, ?, ?)";

        try (Connection conn = DriverManager.getConnection(url, username, password);
             PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setInt(1, score); // Set the response (score)
            stmt.setInt(2, userId); // Set the user ID
            stmt.setInt(3, quizId);  // Set the quiz ID
            stmt.setInt(4, 1);

            stmt.executeUpdate(); // Execute the query
            System.out.println("Response saved to the database.");

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to save response to the database.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void Radio1AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio1AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio1AActionPerformed

    private void Radio1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio1BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio1BActionPerformed

    private void Radio1CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio1CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio1CActionPerformed

    private void Radio3CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio3CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio3CActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        LESSON_11 lesson11 = new LESSON_11();
        lesson11.setVisible(true);

    // Close the current Quiz_11 JFrame
    this.dispose();
    }//GEN-LAST:event_BackActionPerformed
  
    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
    // Validate that each question has a selected answer
    if (!Radio1A.isSelected() && !Radio1B.isSelected() && !Radio1C.isSelected() && !Radio1D.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please select an answer for Question 1.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!Radio2A.isSelected() && !Radio2B.isSelected() && !Radio2C.isSelected() && !Radio2D.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please select an answer for Question 2.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!Radio3A.isSelected() && !Radio3B.isSelected() && !Radio3C.isSelected() && !Radio3D.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please select an answer for Question 3.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!Radio4A.isSelected() && !Radio4B.isSelected() && !Radio4C.isSelected() && !Radio4D.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please select an answer for Question 4.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!Radio5A.isSelected() && !Radio5B.isSelected() && !Radio5C.isSelected() && !Radio5D.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please select an answer for Question 5.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int score = 0;

    // Calculate the score
    if (Radio1B.isSelected()) score++;
    if (Radio2D.isSelected()) score++;
    if (Radio3B.isSelected()) score++;
    if (Radio4B.isSelected()) score++;
    if (Radio5B.isSelected()) score++;

    // Display the score to the user
    JOptionPane.showMessageDialog(this, "Your score: " + score + "/5", "Quiz Result", JOptionPane.INFORMATION_MESSAGE);

    // Retrieve logged-in user ID (Store it in session if not already done)
    int userId = getLoggedInUserId();
    if (userId == -1) {
        return; // Abort if no user is logged in
    }

    // Store the user ID in the session (if not done earlier)
    SessionManager.getSession().put("userId", userId);

    // Save the response to the database
    saveResponseToDatabase(userId, score, quiz_id);

    // Cleanup and redirect to Form_Home
    JOptionPane.showMessageDialog(this, "Thank you for taking the quiz!");
    Form_Home homeForm = new Form_Home();
    homeForm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Quiz_11 quiz = new Quiz_11(1);  // Pass quiz_id = 1
            quiz.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BG1;
    private javax.swing.ButtonGroup BG2;
    private javax.swing.ButtonGroup BG3;
    private javax.swing.ButtonGroup BG4;
    private javax.swing.ButtonGroup BG5;
    private javax.swing.JButton Back;
    private javax.swing.JLabel Question1;
    private javax.swing.JLabel Question2;
    private javax.swing.JLabel Question3;
    private javax.swing.JLabel Question4;
    private javax.swing.JLabel Question5;
    private javax.swing.JLabel Question6;
    private javax.swing.JLabel Question7;
    private javax.swing.JRadioButton Radio1A;
    private javax.swing.JRadioButton Radio1B;
    private javax.swing.JRadioButton Radio1C;
    private javax.swing.JRadioButton Radio1D;
    private javax.swing.JRadioButton Radio2A;
    private javax.swing.JRadioButton Radio2B;
    private javax.swing.JRadioButton Radio2C;
    private javax.swing.JRadioButton Radio2D;
    private javax.swing.JRadioButton Radio3A;
    private javax.swing.JRadioButton Radio3B;
    private javax.swing.JRadioButton Radio3C;
    private javax.swing.JRadioButton Radio3D;
    private javax.swing.JRadioButton Radio4A;
    private javax.swing.JRadioButton Radio4B;
    private javax.swing.JRadioButton Radio4C;
    private javax.swing.JRadioButton Radio4D;
    private javax.swing.JRadioButton Radio5A;
    private javax.swing.JRadioButton Radio5B;
    private javax.swing.JRadioButton Radio5C;
    private javax.swing.JRadioButton Radio5D;
    private javax.swing.JButton Submit;
    // End of variables declaration//GEN-END:variables
}
